# Generated by Django 5.2.17 on 2026-10-04 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('send', 'Send'), ('reconcile', 'Reconcile'), ('delivery', 'Delivery update'), ('clicks', 'Clicks update')], max_length=16)),
                ('state', models.CharField(choices=[('queued', 'Waiting'), ('running', 'Running'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('control', models.CharField(blank=True, choices=[('', ''), ('pause', 'Pause'), ('cancel', 'Cancel')], default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lease_owner', models.CharField(blank=True, max_length=64)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.campaign')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(default='note', max_length=64)),
                ('text', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.job')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['state', 'created_at'], name='jobs_job_state_d065b7_idx'),
        ),
    ]
