# Generated by Django 5.2.17 on 2026-10-04 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='decision',
            field=models.CharField(blank=True, choices=[('', ''), ('approved', 'Approved'), ('rejected', 'Rejected')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='job',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='settings_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('test', 'Test SMS'), ('send', 'Send'), ('reconcile', 'Reconcile'), ('delivery', 'Delivery update'), ('clicks', 'Clicks update')], max_length=16),
        ),
    ]
