# Generated by Django 5.2.17 on 2026-10-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_test_jobs_and_approvals'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=64, unique=True)),
                ('seen_at', models.DateTimeField()),
            ],
        ),
    ]
