# Generated by Django 5.2.17 on 2026-10-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_worker_beat'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='not_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
