# Generated by Django 5.2.17 on 2026-10-05 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_preset'),
        ('jobs', '0005_campaign_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaigns.preset'),
        ),
    ]
