# Generated by Django 5.2.17 on 2026-10-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_rate',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_send_window',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_targets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
