# Generated by Django 5.2.17 on 2026-10-05 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_notify_and_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.BigIntegerField(blank=True, null=True)),
                ('problem', models.CharField(blank=True, max_length=16)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('below_since', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='credit_floor',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sending_held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sending_held_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
