# Generated by Django 5.2.17 on 2026-10-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_hold_and_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='backup_hour',
            field=models.PositiveSmallIntegerField(blank=True, default=9, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='backup_keep',
            field=models.PositiveSmallIntegerField(default=14),
        ),
    ]
