# Generated by Django 5.2.17 on 2026-10-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_daily_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='team_test_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='second_approver',
            field=models.BooleanField(default=False),
        ),
    ]
