# Generated by Django 5.2.17 on 2026-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_test_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='retention_months',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='retention_ran_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='retention_result',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
