# Generated by Django 5.2.17 on 2026-10-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
