# Generated by Django 5.2.17 on 2026-10-04 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to='jobs.campaign')),
            ],
            options={
                'ordering': ['-added_at', '-id'],
                'indexes': [models.Index(fields=['phone'], name='suppression_phone_931725_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('campaign__isnull', True)), fields=('phone',), name='suppression_global_once'), models.UniqueConstraint(fields=('phone', 'campaign'), name='suppression_campaign_once')],
            },
        ),
    ]
