# Generated by Django 5.2.17 on 2026-10-04 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Columns not chosen yet'), ('ready', 'Ready')], default='draft', max_length=8)),
                ('has_header', models.BooleanField(default=True)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('user_id_column', models.CharField(blank=True, max_length=200)),
                ('token_columns', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
