# Generated by Django 5.2.17 on 2026-10-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
