# Generated by Django 5.2.17 on 2026-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0002_segment_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='numbers_removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='status',
            field=models.CharField(choices=[('draft', 'Columns not chosen yet'), ('ready', 'Ready'), ('removed', 'Numbers removed')], default='draft', max_length=8),
        ),
    ]
